version: '3.8'

services:
  web:
    # image: php:8.1-apache
    build: .
    container_name: qmc-web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./php/apache2.conf:/etc/apache2/apache2.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    networks:
      - qmc-network

  mariadb:
    image: mariadb:10.6
    container_name: qmc-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cw_database
      MYSQL_USER: qmc_user
      MYSQL_PASSWORD: qmc_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb/cw-database.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - qmc-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: qmc-pma
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - qmc-network

networks:
  qmc-network:
    driver: bridge